language: java
branches:
  only:
    - develop
script:
    ./gradlew pTML && pushd test && ../gradlew pTML && popd && pushd testConsume && ../gradlew pTML && popd
after_success: git fetch origin master:refs/remotes/origin/master && git checkout -b master origin/master && git merge develop && git push -u origin master
